### ISSUE TITLE
tensorflow logits and labels still not broadcastable

### ISSUE THREAD

**Issue by kishan-sm** [akshaybahadur21/Guitar-Learner#1]
I was trying to play around with this and am getting this error. This error was occuring when using the trainer.py file

````
PS C:\Users\user\Documents\GitHub\Guitar-Learner> python Trainer.py
Found 5760 images belonging to 7 classes.
Found 1440 images belonging to 7 classes.
2021-12-24 14:53:33.420229: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1/5
Traceback (most recent call last):
  File "Trainer.py", line 70, in <module>
    main()
  File "Trainer.py", line 63, in main
    model.fit(train_generator, epochs=5, validation_data=validation_generator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler    
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[64,6] labels_size=[64,7]        
         [[node categorical_crossentropy/softmax_cross_entropy_with_logits
 (defined at C:\Users\userl\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend.py:5009)
]] [Op:__inference_train_function_844]

Errors may have originated from an input operation.
Input Source operations connected to node categorical_crossentropy/softmax_cross_entropy_with_logits:
In[0] categorical_crossentropy/softmax_cross_entropy_with_logits/Reshape:
In[1] categorical_crossentropy/softmax_cross_entropy_with_logits/Reshape_1:

Operation defined at: (most recent call last)
>>>   File "Trainer.py", line 70, in <module>
>>>     main()
>>> 
>>>   File "Trainer.py", line 63, in main
>>>     model.fit(train_generator, epochs=5, validation_data=validation_generator)
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 878, in train_function    
>>>     return step_function(self, iterator)
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 867, in step_function     
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 809, in train_step        
>>>     loss = self.compiled_loss(
>>>
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
>>>     loss_value = loss_obj(y_t, y_p, sample_weight=sw)
>>>
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\losses.py", line 141, in __call__
>>>     losses = call_fn(y_true, y_pred)
>>>
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\losses.py", line 245, in call
>>>     return ag_fn(y_true, y_pred, **self._fn_kwargs)
>>>
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\losses.py", line 1664, in categorical_crossentropy
>>>     return backend.categorical_crossentropy(
>>>
>>>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\backend.py", line 5009, in categorical_crossentropy
>>>     return tf.nn.softmax_cross_entropy_with_logits(
>>>
2021-12-24 14:53:36.156804: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]`
```

**Comment by GMPlayss** [comment]
it says that it cannot locate the .h5 file and I cannot find where it is
